[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fitz>=0.0.1.dev2",
    "numpy>=2.2.2",
    "opencv-python>=4.11.0.86",
    "pymupdf>=1.25.2",
    "streamlit>=1.42.0",
]
